clear
close all
clc

tic

%load('Failure_model_inputs')

tbl  = readtable('Failure_model_inputs.csv');
S    = table2struct(tbl,'ToScalar',true);
names = fieldnames(S);
for k = 1:numel(names)
    assignin('base',names{k},S.(names{k}));
end

load('Fragility_interp.mat','sw_fun','turbine_fun','tr_fun')
load('US_hourly_electricity_demand','demand')
load('Joint_Failure_Functon.mat','jointFailure')
load('Seismic_fragility_electrical.mat','cb_fun','transformer_fun')
evalc('SMDFR_Parameters');

[ACS_1,ACS_2,ACS_3,ACS_4,LOCA1_time,LOCA2_time,LOCA3_time,...
                LOCA4_time,EDG_1,EDG_2,Power,alpha_1,alpha_2,alpha_3,alpha_4,...
                ACS_initial,pipes_initial,EDG_initial,EDG_1_corrosion,EDG_1_earthquake,...
                ACS_1_corrosion,ACS_1_earthquake,CP_corrosion,CP_earthquake,PDP11,PDP12,...
                PDP21,PDP22,PDP31,PDP32,PDP41,PDP42,MSLB1,MSLB2,MSLB3,MSLB4,...
                LOP_earthquake,LOP_hydrogen,MSLB1_hydrogen,MSLB2_hydrogen,MSLB3_hydrogen,...
                MSLB4_hydrogen, MSLB_earthquake,LHS,LHS_explosion,LHS_overcurrent,...
                thermal_failure, thermal_failure_time] = Failure_sim_HTE_model (age,PGA,PGA,sigma_C_C,sigma_R_C,sigma_C_ACS,sigma_R_ACS, ...
                t_min_EDG,t_max_EDG,t_min_ACS,t_max_ACS, ...
                maint_effectiveness,mu_l_in_ACS,mu_l_in_CP,sigma_l_in_ACS,sigma_l_in_CP,mu_l_in_EDG, ...
                sigma_l_in_EDG,distance,sw_fun,cb_fun,transformer_fun,tr_fun,turbine_fun,demand,jointFailure);


%Response time of ACS [s]
t_min_r_ACS = 30; %minimum value of the response time
t_max_r_ACS = 90; %maximum value of the response time

%Response time of EDG [s]
t_min_r_EDG = 10; %minimum value of the response time
t_max_r_EDG = 180; %maximum value of the response time

ACS1_response_time = randi(t_max_r_ACS-t_min_r_ACS)+t_min_r_ACS;
ACS2_response_time = randi(t_max_r_ACS-t_min_r_ACS)+t_min_r_ACS;
ACS3_response_time = randi(t_max_r_ACS-t_min_r_ACS)+t_min_r_ACS;
ACS4_response_time = randi(t_max_r_ACS-t_min_r_ACS)+t_min_r_ACS;
EDG1_response_time = randi(t_max_r_EDG-t_min_r_EDG)+t_min_r_EDG;
EDG2_response_time = randi(t_max_r_EDG-t_min_r_EDG)+t_min_r_EDG;
PDP11_response_time = randi(t_max_r_EDG-t_min_r_EDG)+t_min_r_EDG;
PDP12_response_time = randi(t_max_r_EDG-t_min_r_EDG)+t_min_r_EDG;
PDP21_response_time = randi(t_max_r_EDG-t_min_r_EDG)+t_min_r_EDG;
PDP22_response_time = randi(t_max_r_EDG-t_min_r_EDG)+t_min_r_EDG;
PDP31_response_time = randi(t_max_r_EDG-t_min_r_EDG)+t_min_r_EDG;
PDP32_response_time = randi(t_max_r_EDG-t_min_r_EDG)+t_min_r_EDG;
PDP41_response_time = randi(t_max_r_EDG-t_min_r_EDG)+t_min_r_EDG;
PDP42_response_time = randi(t_max_r_EDG-t_min_r_EDG)+t_min_r_EDG;

save('Failure_model_outputs.mat', ...
    'ACS_1','ACS_2','ACS_3','ACS_4', ...
    'LOCA1_time','LOCA2_time','LOCA3_time','LOCA4_time', ...
    'EDG_1','EDG_2','Power', ...
    'alpha_1','alpha_2','alpha_3','alpha_4', ...
    'ACS_initial','pipes_initial','EDG_initial', ...
    'PDP11','PDP12','PDP21','PDP22','PDP31','PDP32','PDP41','PDP42', ...
    'MSLB1','MSLB2','MSLB3','MSLB4', ...
    'LOP_earthquake','LOP_hydrogen', ...
    'MSLB1_hydrogen','MSLB2_hydrogen','MSLB3_hydrogen','MSLB4_hydrogen', ...
    'MSLB_earthquake','LHS','LHS_explosion','LHS_overcurrent', ...
    'thermal_failure','thermal_failure_time', ...
    'ACS1_response_time','ACS2_response_time','ACS3_response_time','ACS4_response_time', ...
    'EDG1_response_time','EDG2_response_time', ...
    'PDP11_response_time','PDP12_response_time','PDP21_response_time','PDP22_response_time', ...
    'PDP31_response_time','PDP32_response_time','PDP41_response_time','PDP42_response_time','PGA');

%% Gather the variables you just calculated
ACS_1_initial = ACS_initial(1);
ACS_2_initial = ACS_initial(2);
ACS_3_initial = ACS_initial(3);
ACS_4_initial = ACS_initial(4);
pipes_1_initial = pipes_initial(1);
pipes_2_initial = pipes_initial(2);
pipes_3_initial = pipes_initial(3);
pipes_4_initial = pipes_initial(4);
EDG_1_initial = EDG_initial(1);
EDG_2_initial = EDG_initial(2);

results = table( ...
    ACS_1,ACS_2,ACS_3,ACS_4, ...
    LOCA1_time,LOCA2_time,LOCA3_time,LOCA4_time, ...
    EDG_1,EDG_2,Power, ...
    alpha_1,alpha_2,alpha_3,alpha_4, ...
    ACS_1_initial,ACS_2_initial,ACS_3_initial,ACS_4_initial,...
    pipes_1_initial,pipes_2_initial,pipes_3_initial,pipes_4_initial,EDG_1_initial,EDG_2_initial, ...
    PDP11,PDP12,PDP21,PDP22,PDP31,PDP32,PDP41,PDP42, ...
    MSLB1,MSLB2,MSLB3,MSLB4, ...
    LOP_earthquake,LOP_hydrogen, ...
    MSLB1_hydrogen,MSLB2_hydrogen,MSLB3_hydrogen,MSLB4_hydrogen, ...
    MSLB_earthquake,LHS,LHS_explosion,LHS_overcurrent, ...
    thermal_failure,thermal_failure_time, ...
    ACS1_response_time,ACS2_response_time,ACS3_response_time,ACS4_response_time, ...
    EDG1_response_time,EDG2_response_time, ...
    PDP11_response_time,PDP12_response_time,PDP21_response_time,PDP22_response_time, ...
    PDP31_response_time,PDP32_response_time,PDP41_response_time,PDP42_response_time, ...
    PGA);

%% Write to CSV
writetable(results,'Failure_model_outputs.csv');

toc